"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { ArrowDown,ArrowRight,ArrowUpRight,Clock3,MapPin,Sparkles,Star } from "lucide-react";
import { categories } from "@/data/restaurants";
import { useApp } from "@/components/app-provider";
import { FoodImage,RestaurantCard,SearchBox,SectionTitle } from "@/components/ui";

export default function Home(){const [query,setQuery]=useState(""),[category,setCategory]=useState("All"),[sort,setSort]=useState("Recommended"),[filter,setFilter]=useState("All restaurants");const {mode,location,restaurants}=useApp();
 const filtered=useMemo(()=>{let list=restaurants.filter(r=>{const q=query.trim().toLowerCase();const match=!q||r.name.toLowerCase().includes(q)||r.cuisine.join(" ").toLowerCase().includes(q)||r.tags.join(" ").toLowerCase().includes(q)||r.dishes.some(d=>d.name.toLowerCase().includes(q)||d.description.toLowerCase().includes(q));const hasDeal=r.promotion?.toLowerCase().includes("off")||r.promotion?.toLowerCase().includes("free delivery");return match&&(category==="All"||r.cuisine.includes(category)||r.dishes.some(d=>d.category===category))&&(filter!=="Top rated"||r.rating>=4.7)&&(filter!=="Under 30 min"||r.deliveryMinutes<30)&&(filter!=="Deals"||!!hasDeal)}) ;if(sort==="Rating")list=list.toSorted((a,b)=>b.rating-a.rating);if(sort==="Fastest")list=list.toSorted((a,b)=>a.deliveryMinutes-b.deliveryMinutes);if(sort==="Delivery fee")list=list.toSorted((a,b)=>a.deliveryFee-b.deliveryFee);return list},[query,category,sort,filter,restaurants]);
 const featured=restaurants.slice(0,8);return <>
  <section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><span className="hero-kicker"><span className="sparkle">✳</span> YOUR CITY. YOUR CRAVINGS.</span><h1>Good food<br/>finds <em>you.</em></h1><p>From Sarawak laksa to late-night bites, Kuching’s best flavours are just a few taps away.</p><div className="hero-search"><SearchBox value={query} onChange={setQuery} placeholder="Try ‘Sarawak laksa’ or ‘kolo mee’"/><button onClick={()=>document.getElementById("restaurants")?.scrollIntoView({behavior:"smooth"})}>Find food <ArrowRight size={16}/></button></div><div className="hero-notes"><span><span className="note-check">✓</span> Local favourites</span><i>·</i><span><span className="note-check">✓</span> Easy ordering</span><i>·</i><span><span className="note-check">✓</span> Your way</span></div></div><div className="hero-art"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-food"><FoodImage src="https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1000&q=90" alt="A bowl of colourful noodles"/></div><div className="floating-note note-rating"><span className="note-stars">★★★★★</span><b>Local love</b><small>made fresh nearby</small></div><div className="floating-note note-time"><span className="time-icon"><Clock3 size={17}/></span><span><b>From 22 min</b><small>to your door</small></span></div><span className="hero-sticker">made<br/>for <b>you</b></span><div className="hero-caption"><span>✦</span> A little taste of Kuching</div></div></div><div className="hero-bottom wrap"><span><MapPin size={15}/> Finding good food around <b>{location}</b></span><a href="#restaurants">Scroll to explore <ArrowDown size={14}/></a></div></section>
  <section className="wrap category-section"><div className="category-head"><div><span className="eyebrow">WHAT SOUNDS GOOD?</span><h2>Pick your craving</h2></div><span className="category-hint">A little something for every mood <span>↗</span></span></div><div className="category-row"><button className={`category-pill ${category==="All"?"active":""}`} onClick={()=>setCategory("All")}><span className="cat-emoji">✦</span>All food</button>{categories.map((c,i)=><button key={c} className={`category-pill ${category===c?"active":""}`} onClick={()=>{setCategory(category===c?"All":c);document.getElementById("restaurants")?.scrollIntoView({behavior:"smooth"})}}><span className="cat-emoji">{["🌿","🍛","🍜","🍚","🍗","🦐","🥢","🌶️","☕","🍰","🥐","🍔"][i]}</span>{c}</button>)}</div></section>
  <section className="featured-band"><div className="wrap"><SectionTitle eyebrow="A GOOD PLACE TO START" title="Kuching, served fresh" more="See all restaurants"/><div className="featured-grid">{featured.slice(0,4).map((r,i)=><Link href={`/restaurant/${r.slug}`} className={`featured-tile tile-${i+1}`} key={r.id}><FoodImage src={r.image} alt={r.name}/><div className="tile-shade"/><span className="tile-number">0{i+1} / LOCAL PICK</span><div className="tile-copy"><span>{r.cuisine[0]} · {r.tags[0]}</span><h3>{r.name}</h3><div><span><Star size={13} fill="currentColor"/>{r.rating.toFixed(1)}</span><i>·</i><span><Clock3 size={13}/>{mode==="Delivery"?r.deliveryMinutes:r.pickupMinutes} min</span></div></div><span className="tile-arrow"><ArrowUpRight size={18}/></span></Link>)}</div></div></section>
  <section className="wrap listing-section" id="restaurants"><SectionTitle eyebrow="YOUR NEXT GREAT MEAL" title="Good things nearby"/><p className="listing-sub">A few local favourites, ready when you are. <span>Showing {filtered.length} spots around {location}</span></p><div className="listing-tools"><div className="filter-chips">{["All restaurants","Top rated","Under 30 min","Deals"].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?"active":""}>{f==="Top rated"&&<Star size={13}/>} {f==="Under 30 min"&&<Clock3 size={13}/>} {f==="Deals"&&<Sparkles size={13}/>} {f}</button>)}</div><label className="sort-control">Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Rating</option><option>Fastest</option><option>Delivery fee</option></select></label></div><div className="listing-search"><SearchBox value={query} onChange={setQuery} placeholder="Search restaurants, dishes and cuisines"/><button className="clear-filters" onClick={()=>{setCategory("All");setFilter("All restaurants");setSort("Recommended");setQuery("")}}>Clear all</button></div>{category!=="All"&&<button className="active-category" onClick={()=>setCategory("All")}>{category} <span>×</span></button>}{filtered.length?<div className="restaurant-grid">{filtered.map(r=><RestaurantCard key={r.id} restaurant={r}/>)}</div>:<div className="empty-results"><span>⌕</span><h3>No bites found just yet</h3><p>Try another search or clear your filters to see all the good stuff.</p><button className="button primary" onClick={()=>{setQuery("");setFilter("All restaurants");setCategory("All")}}>Show all restaurants</button></div>}</section>
  <section className="local-banner"><div className="wrap local-banner-inner"><div><span className="eyebrow">FROM SARAWAK, WITH LOVE</span><h2>A city with a<br/><em>taste of its own.</em></h2><p>Discover the comfort of familiar flavours and the joy of finding a new favourite.</p><a href="#restaurants" className="button white-button">Explore local favourites <ArrowRight size={16}/></a></div><div className="banner-photo"><FoodImage src="https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=85" alt="A colourful rice bowl"/><span className="banner-stamp">KCH<br/><small>01°33′N</small></span></div></div></section>
  <section className="wrap reassurance"><div><span className="reassurance-icon">✦</span><span><b>Made for Kuching</b><small>Local flavours, local favourites</small></span></div><div><span className="reassurance-icon">↗</span><span><b>Easy from start to finish</b><small>Browse, choose, enjoy</small></span></div><div><span className="reassurance-icon">♡</span><span><b>A little something for everyone</b><small>Find your kind of delicious</small></span></div></section>
 </>}
