"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {api,ApiError} from "@/lib/api";
import {useApp} from "@/components/app-provider";
import {money} from "@/lib/cart";
type Dashboard={ordersToday:number;revenueToday:number;pendingOrders:number;preparingOrders:number;completedOrders:number;cancelledOrders:number;registeredCustomers:number;activeRestaurants:number;averageOrderValue:number;recentOrders:AdminOrder[];dailyRevenue:{date:string;revenue:number}[]};
type AdminOrder={reference:string;customerName:string;customerPhone:string;restaurant:string;fulfilment:string;status:string;paymentMethod:string;paymentStatus:string;total:number;placedAt:string};
type Restaurant={id:number;name:string;slug:string;area:string;status:string;featured:boolean;menuItemsCount:number|null;deliveryFee:number;minimumOrder:number};
type Item={id:number;name:string;description:string;category:string|null;categoryId:number|null;price:number;image:string;available:boolean;popular:boolean;modifierGroups:unknown[]};
type Category={id:number;name:string;active:boolean;sort_order:number};
type Customer={id:number;name:string;email:string;phone:string|null;orderCount:number;totalSpend:number;registeredAt:string};
type Promo={id:number;code:string;title:string;type:string;value:number;active:boolean;redeemedCount:number};
const tabs=["Overview","Orders","Restaurants & menu","Customers","Promotions","Settings"] as const;type Tab=typeof tabs[number];
const nextStatus:Record<string,string[]>={pending:["confirmed","cancelled"],confirmed:["preparing","cancelled"],preparing:["rider_assigned","ready_for_pickup","cancelled"],rider_assigned:["picked_up"],ready_for_pickup:["picked_up"],picked_up:["on_the_way"],on_the_way:["delivered"]};
export default function AdminPage(){const router=useRouter();const {user,authReady,refreshUser}=useApp();const [tab,setTab]=useState<Tab>("Overview"),[data,setData]=useState<unknown>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[restaurants,setRestaurants]=useState<Restaurant[]>([]),[selectedRestaurant,setSelectedRestaurant]=useState(""),[items,setItems]=useState<Item[]>([]),[categories,setCategories]=useState<Category[]>([]),[search,setSearch]=useState("");
 useEffect(()=>{if(authReady&&(!user||user.role!=="admin"))router.replace("/admin/login")},[authReady,user,router]);
 async function load(){if(!user||user.role!=="admin")return;setError("");try{if(tab==="Overview")setData((await api<{data:Dashboard}>("/api/admin/dashboard")).data);if(tab==="Orders")setData((await api<{data:{data:AdminOrder[]}}>("/api/admin/orders")).data.data);if(tab==="Restaurants & menu"){const list=(await api<{data:{data:Restaurant[]}}>("/api/admin/restaurants")).data.data;setRestaurants(list);setSelectedRestaurant(old=>old||String(list[0]?.id||""));setData(list)}if(tab==="Customers")setData((await api<{data:{data:Customer[]}}>("/api/admin/customers")).data.data);if(tab==="Promotions")setData((await api<{data:{data:Promo[]}}>("/api/admin/promotions")).data.data);if(tab==="Settings")setData((await api<{data:Record<string,unknown>}>("/api/admin/settings")).data)}catch(e){setError(e instanceof ApiError?e.message:"We couldn't load the admin view.")}}
 useEffect(()=>{void load()},[tab,user?.id]);
 useEffect(()=>{if(tab!=="Restaurants & menu"||!selectedRestaurant)return;void Promise.all([api<{data:{data:Item[]}}>(`/api/admin/restaurants/${selectedRestaurant}/items`),api<{data:Category[]}>(`/api/admin/restaurants/${selectedRestaurant}/categories`)]).then(([itemsResult,categoriesResult])=>{setItems(itemsResult.data.data);setCategories(categoriesResult.data)}).catch(()=>setError("Couldn't load this menu."))},[tab,selectedRestaurant]);
 async function action(path:string,method:string,body?:unknown){setBusy(true);setError("");try{await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});await load();if(tab==="Restaurants & menu"&&selectedRestaurant){const r=await api<{data:{data:Item[]}}>(`/api/admin/restaurants/${selectedRestaurant}/items`);setItems(r.data.data)}}catch(e){setError(e instanceof ApiError?e.message:"That change could not be saved.")}finally{setBusy(false)}}
 async function logout(){await api("/api/logout",{method:"POST"}).catch(()=>{});await refreshUser();router.replace("/admin/login")}
 if(!authReady||!user||user.role!=="admin")return <div className="wrap all-restaurants">Opening FuudGo operations…</div>;
 const stats=data as Dashboard|null;return <div className="wrap admin-shell"><aside className="admin-sidebar"><Link href="/" className="brand"><span className="brand-mark">f<span>g</span></span><span>fuud<span>go</span><small>OPERATIONS</small></span></Link><nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav><button className="button secondary" onClick={logout}>Sign out</button></aside><section className="admin-main"><header className="admin-top"><div><span className="eyebrow">KUCHING OPERATIONS</span><h1>{tab}</h1></div><span>{busy?"Saving changes…":"Signed in as "}<b>{user.name}</b></span></header>{error&&<p role="alert" className="error-text">{error}</p>}
 {tab==="Overview"&&stats&&<><div className="admin-metrics">{[["Orders today",stats.ordersToday],["Revenue today",money(stats.revenueToday)],["Needs attention",stats.pendingOrders],["Preparing",stats.preparingOrders],["Customers",stats.registeredCustomers],["Active restaurants",stats.activeRestaurants],["Completed",stats.completedOrders],["Average order",money(stats.averageOrderValue)]].map(([label,value])=><article className="admin-metric" key={String(label)}><small>{label}</small><b>{value}</b></article>)}</div><section className="admin-panel"><h2>Recent orders</h2><OrderTable orders={stats.recentOrders} update={async(o,status)=>{if(status==="cancelled"&&!confirm(`Cancel ${o.reference}?`))return;await action(`/api/admin/orders/${o.reference}/status`,"PATCH",{status,...(status==="cancelled"?{confirm_cancel:true}:{})})}}/></section><section className="admin-panel"><h2>Revenue · last 7 days</h2><div className="revenue-bars">{stats.dailyRevenue.map(d=><div key={d.date} title={`${d.date}: ${money(d.revenue)}`}><span style={{height:`${Math.max(4,d.revenue/(Math.max(1,...stats.dailyRevenue.map(x=>x.revenue))*100))}%`}}/><small>{new Date(d.date).toLocaleDateString(undefined,{weekday:"short"})}</small></div>)}</div></section></>}
 {tab==="Orders"&&<section className="admin-panel"><div className="admin-panel-heading"><h2>Incoming and recent orders</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search orders" aria-label="Search orders"/></div><OrderTable orders={(data as AdminOrder[]||[]).filter(o=>`${o.reference} ${o.customerName} ${o.restaurant}`.toLowerCase().includes(search.toLowerCase()))} update={async(o,status)=>{if(status==="cancelled"&&!confirm(`Cancel ${o.reference}?`))return;await action(`/api/admin/orders/${o.reference}/status`,"PATCH",{status,...(status==="cancelled"?{confirm_cancel:true}:{})})}}/></section>}
 {tab==="Restaurants & menu"&&<><section className="admin-panel"><div className="admin-panel-heading"><h2>Restaurants</h2><RestaurantCreate created={()=>void load()}/></div><div className="admin-list">{restaurants.map(r=><div className="admin-row" key={r.id}><div><b>{r.name}</b><small>{r.area} · {r.menuItemsCount??0} dishes · {r.status}{r.slug?` · /${r.slug}`:""}</small></div><div className="admin-row-actions"><button className="button secondary" onClick={()=>void action(`/api/admin/restaurants/${r.id}/status`,"PATCH",{status:r.status==="active"?"inactive":"active"})}>{r.status==="active"?"Pause":"Activate"}</button><button className="button secondary" onClick={()=>setSelectedRestaurant(String(r.id))}>Manage menu</button></div></div>)}</div></section>{selectedRestaurant&&<section className="admin-panel"><div className="admin-panel-heading"><h2>Menu items and categories</h2><select aria-label="Choose restaurant" value={selectedRestaurant} onChange={e=>setSelectedRestaurant(e.target.value)}>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><CategoryCreate restaurantId={selectedRestaurant} created={async()=>{const r=await api<{data:Category[]}>(`/api/admin/restaurants/${selectedRestaurant}/categories`);setCategories(r.data)}}/><ItemCreate restaurantId={selectedRestaurant} categories={categories} onDone={async()=>{const r=await api<{data:{data:Item[]}}>(`/api/admin/restaurants/${selectedRestaurant}/items`);setItems(r.data.data)}}/><div className="admin-list">{items.map(i=><div className="admin-row" key={i.id}><div><b>{i.name}</b><small>{i.category||"Uncategorised"} · {money(i.price)} · {i.available?"Available":"Paused"}{i.modifierGroups.length?` · ${i.modifierGroups.length} customisation groups`:""}</small></div><div className="admin-row-actions"><button className="button secondary" onClick={()=>void action(`/api/admin/items/${i.id}/availability`,"PATCH",{available:!i.available})}>{i.available?"Pause item":"Enable item"}</button><button className="button secondary" onClick={()=>void action(`/api/admin/items/${i.id}/duplicate`,"POST",{})}>Duplicate</button><button className="button secondary" onClick={()=>confirm(`Archive ${i.name}?`)&&void action(`/api/admin/items/${i.id}`,"DELETE")}>Archive</button></div></div>)}</div></section>}</>}
 {tab==="Customers"&&<section className="admin-panel"><h2>Customers</h2><div className="admin-list">{(data as Customer[]||[]).map(c=><div className="admin-row" key={c.id}><div><b>{c.name}</b><small>{c.email} · {c.phone||"No phone"} · Joined {new Date(c.registeredAt).toLocaleDateString()}</small></div><strong>{c.orderCount} orders · {money(c.totalSpend)}</strong></div>)}</div></section>}
 {tab==="Promotions"&&<><section className="admin-panel"><h2>Create a promotion</h2><PromotionCreate created={()=>void load()}/></section><section className="admin-panel"><h2>Current promotions</h2><div className="admin-list">{(data as Promo[]||[]).map(p=><div className="admin-row" key={p.id}><div><b>{p.code} · {p.title}</b><small>{p.type.replaceAll("_"," ")} · {p.type==="percentage"?`${p.value}%`:p.type==="fixed"?money(p.value):"Free delivery"} · used {p.redeemedCount} times</small></div><button className="button secondary" onClick={()=>void action(`/api/admin/promotions/${p.id}`,"DELETE")}>{p.active?"Deactivate":"Remove"}</button></div>)}</div></section></>}
 {tab==="Settings"&&<SettingsForm initial={data as Record<string,unknown>|null} save={async body=>{await action("/api/admin/settings","PATCH",body)}}/>}
 </section></div>
}

function OrderTable({orders,update}:{orders:AdminOrder[];update:(order:AdminOrder,status:string)=>Promise<void>}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Restaurant</th><th>Total</th><th>Status</th><th>Update</th></tr></thead><tbody>{orders.map(o=><tr key={o.reference}><td><b>{o.reference}</b><small>{new Date(o.placedAt).toLocaleString()}</small></td><td>{o.customerName}<small>{o.customerPhone}</small></td><td>{o.restaurant}<small>{o.fulfilment} · {o.paymentStatus}</small></td><td>{money(o.total)}</td><td>{o.status.replaceAll("_"," ")}</td><td><select aria-label={`Update ${o.reference}`} value="" onChange={e=>{if(e.target.value)void update(o,e.target.value)}} disabled={!nextStatus[o.status]?.length}><option value="">Choose next</option>{(nextStatus[o.status]||[]).map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></td></tr>)}</tbody></table>{!orders.length&&<p>No orders yet.</p>}</div>}
function RestaurantCreate({created}:{created:()=>void}){const [open,setOpen]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{const data={name:fd.get("name"),slug:fd.get("slug"),description:fd.get("description"),cuisines:String(fd.get("cuisines")).split(",").map(s=>s.trim()).filter(Boolean),tags:String(fd.get("tags")).split(",").map(s=>s.trim()).filter(Boolean),area:fd.get("area"),delivery_minutes:Number(fd.get("delivery_minutes")),pickup_minutes:Number(fd.get("pickup_minutes")),delivery_fee:Number(fd.get("delivery_fee")),minimum_order:Number(fd.get("minimum_order")),cover_image_url:fd.get("cover_image_url")||null};await api("/api/admin/restaurants",{method:"POST",body:JSON.stringify(data)});setOpen(false);setError("");created()}catch(err){setError(err instanceof ApiError?err.message:"Restaurant could not be created.")}}return <div><button className="button primary" onClick={()=>setOpen(v=>!v)}>Add restaurant</button>{open&&<form className="admin-form" onSubmit={submit}><input name="name" placeholder="Restaurant name" required/><input name="slug" placeholder="URL slug (optional)"/><input name="area" placeholder="Kuching area" required/><input name="cuisines" placeholder="Cuisines, comma separated" required/><input name="tags" placeholder="Tags, comma separated"/><textarea name="description" placeholder="Short description"/><input name="cover_image_url" type="url" placeholder="Cover image URL"/><label>Delivery minutes<input name="delivery_minutes" type="number" defaultValue="35" required/></label><label>Pickup minutes<input name="pickup_minutes" type="number" defaultValue="15" required/></label><label>Delivery fee RM<input name="delivery_fee" type="number" step="0.01" defaultValue="3.5" required/></label><label>Minimum order RM<input name="minimum_order" type="number" step="0.01" defaultValue="0" required/></label>{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary">Create restaurant</button></form>}</div>}
function CategoryCreate({restaurantId,created}:{restaurantId:string;created:()=>void}){const [open,setOpen]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api(`/api/admin/restaurants/${restaurantId}/categories`,{method:"POST",body:JSON.stringify({name:fd.get("name"),active:true})});setOpen(false);created()}catch(err){setError(err instanceof ApiError?err.message:"Category could not be created.")}}return <div><button className="button secondary" onClick={()=>setOpen(v=>!v)}>Add category</button>{open&&<form className="admin-form" onSubmit={submit}><input name="name" placeholder="Category name" required/>{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary">Save category</button></form>}</div>}
function ItemCreate({restaurantId,categories,onDone}:{restaurantId:string;categories:Category[];onDone:()=>void}){const [open,setOpen]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);let modifiers:unknown[]=[];try{modifiers=fd.get("modifier_groups_json")?JSON.parse(String(fd.get("modifier_groups_json"))):[]}catch{setError("Modifier groups need valid JSON.");return}try{await api(`/api/admin/restaurants/${restaurantId}/items`,{method:"POST",body:JSON.stringify({name:fd.get("name"),description:fd.get("description"),price:Number(fd.get("price")),image_url:fd.get("image_url")||null,menu_category_id:fd.get("menu_category_id")?Number(fd.get("menu_category_id")):null,dietary_tags:[],modifier_groups:modifiers,available:true,popular:fd.get("popular")==="on"})});setOpen(false);setError("");onDone()}catch(err){setError(err instanceof ApiError?err.message:"Menu item could not be created.")}}return <div><button className="button primary" onClick={()=>setOpen(v=>!v)}>Add menu item</button>{open&&<form className="admin-form" onSubmit={submit}><input name="name" placeholder="Dish name" required/><textarea name="description" placeholder="Description"/>{categories.length>0&&<select name="menu_category_id" defaultValue=""><option value="">Choose category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<label>Price RM<input name="price" type="number" min="0.01" step="0.01" required/></label><input name="image_url" type="url" placeholder="Dish image URL"/><textarea name="modifier_groups_json" placeholder='Optional modifier groups as JSON: [{"name":"Extras","required":false,"minimum_selections":0,"maximum_selections":2,"options":[{"name":"Extra egg","price_adjustment":2}]}]'/><label><input type="checkbox" name="popular"/> Mark as popular</label>{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary">Create dish</button></form>}</div>}
function PromotionCreate({created}:{created:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api("/api/admin/promotions",{method:"POST",body:JSON.stringify({code:fd.get("code"),title:fd.get("title"),type:fd.get("type"),value:Number(fd.get("value")),minimum_spend:Number(fd.get("minimum_spend")),uses_per_customer:1,active:true})});e.currentTarget.reset();setError("");created()}catch(err){setError(err instanceof ApiError?err.message:"Promotion could not be created.")}}return <form className="admin-form" onSubmit={submit}><input name="code" placeholder="Code" required/><input name="title" placeholder="Customer-facing title" required/><select name="type"><option value="percentage">Percentage</option><option value="fixed">Fixed RM</option><option value="free_delivery">Free delivery</option></select><label>Value<input name="value" type="number" step="0.01" defaultValue="10"/></label><label>Minimum spend RM<input name="minimum_spend" type="number" step="0.01" defaultValue="0"/></label>{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary">Create promotion</button></form>}
function SettingsForm({initial,save}:{initial:Record<string,unknown>|null;save:(body:Record<string,unknown>)=>Promise<void>}){const [message,setMessage]=useState("");return <section className="admin-panel"><h2>Ordering settings</h2>{initial&&<form className="admin-form" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);await save({business_name:fd.get("business_name"),support_email:fd.get("support_email"),default_delivery_fee:Number(fd.get("default_delivery_fee")),ordering_enabled:fd.get("ordering_enabled")==="on",cod_enabled:fd.get("cod_enabled")==="on"});setMessage("Settings saved.")}}><label>Business name<input name="business_name" defaultValue={String(initial.business_name||"FuudGo")}/></label><label>Support email<input name="support_email" type="email" defaultValue={String(initial.support_email||"")}/></label><label>Default delivery fee RM<input name="default_delivery_fee" type="number" step="0.01" defaultValue={String(initial.default_delivery_fee??3)}/></label><label><input type="checkbox" name="ordering_enabled" defaultChecked={Boolean(initial.ordering_enabled)}/> Accept new orders</label><label><input type="checkbox" name="cod_enabled" defaultChecked={Boolean(initial.cod_enabled)}/> Cash payments enabled</label><p>Online payments are disabled until a provider is configured.</p>{message&&<p role="status">{message}</p>}<button className="button primary">Save settings</button></form>}</section>}
