"use client";
import { createContext,useCallback,useContext,useEffect,useMemo,useRef,useState } from "react";
import type { CartLine, Dish, ModifierSelection, Order } from "@/types";
import { restaurants,locations } from "@/data/restaurants";
import { api, type ApiUser } from "@/lib/api";
type Mode="Delivery"|"Pickup";
type ContextType={cart:CartLine[];mode:Mode;setMode:(m:Mode)=>void;location:string;setLocation:(l:string)=>void;pending:Dish|null;pendingRestaurant:string;add:(restaurantId:string,dish:Dish,modifiers?:ModifierSelection[])=>void;resolve:(yes:boolean)=>void;setQty:(key:string,n:number)=>void;remove:(key:string)=>void;clear:()=>void;order:Order|null;place:(o:Order)=>void;savedIds:string[];toggleSaved:(id:string)=>void;soundsEnabled:boolean;setSoundsEnabled:(enabled:boolean)=>void;restaurants:typeof restaurants;user:ApiUser|null;authReady:boolean;refreshUser:()=>Promise<void>};
const Context=createContext<ContextType|null>(null);
export function AppProvider({children}:{children:React.ReactNode}){
 const [cart,setCart]=useState<CartLine[]>([]),[mode,setModeState]=useState<Mode>("Delivery"),[location,setLocation]=useState(locations[0]),[pending,setPending]=useState<Dish|null>(null),[pendingRestaurant,setPendingRestaurant]=useState(""),[pendingModifiers,setPendingModifiers]=useState<ModifierSelection[]>([]),[order,setOrder]=useState<Order|null>(null),[savedIds,setSavedIds]=useState<string[]>([]),[soundsEnabled,setSoundsEnabledState]=useState(true),[ready,setReady]=useState(false),[catalog,setCatalog]=useState<typeof restaurants>(restaurants),[catalogReady,setCatalogReady]=useState(false),[user,setUser]=useState<ApiUser|null>(null),[authReady,setAuthReady]=useState(false);
 const audioRef=useRef<AudioContext|null>(null);
 useEffect(()=>{try{const c=localStorage.getItem("fuudgo-cart");if(c)setCart(JSON.parse(c));const m=localStorage.getItem("fuudgo-mode") as Mode|null;if(m)setModeState(m);const l=localStorage.getItem("fuudgo-location");if(l)setLocation(l);const saved=localStorage.getItem("fuudgo-saved");if(saved)setSavedIds(JSON.parse(saved));const sound=localStorage.getItem("fuudgo-sounds");if(sound!==null)setSoundsEnabledState(sound==="true");const o=sessionStorage.getItem("fuudgo-order");if(o)setOrder(JSON.parse(o));}catch{}setReady(true)},[]);
 useEffect(()=>{void api<{data:typeof restaurants}>("/api/restaurants?per_page=40").then(r=>{if(r.data.length)setCatalog(r.data)}).catch(()=>{}).finally(()=>setCatalogReady(true));void api<{user:ApiUser}>("/api/user").then(r=>setUser(r.user)).catch(()=>setUser(null)).finally(()=>setAuthReady(true))},[]);
 const migratedCart=useRef(false);
 useEffect(()=>{if(!ready||!catalogReady||migratedCart.current)return;migratedCart.current=true;setCart(old=>old.map(line=>{const legacyRestaurant=restaurants.find(r=>r.id===line.restaurantId);const actualRestaurant=catalog.find(r=>r.id===line.restaurantId)||catalog.find(r=>r.slug===legacyRestaurant?.slug);if(!actualRestaurant)return line;const legacyDish=legacyRestaurant?.dishes.find(d=>d.id===line.dish.id)||legacyRestaurant?.dishes.find(d=>d.name===line.dish.name);const actualDish=actualRestaurant.dishes.find(d=>d.id===line.dish.id)||actualRestaurant.dishes.find(d=>d.name===line.dish.name)||actualRestaurant.dishes.find(d=>d.name===legacyDish?.name);if(!actualDish)return line;const modifiers=line.modifiers||[];const modifierKey=modifiers.map(g=>g.groupId+":"+g.options.map(o=>o.id).sort().join(",")).join("|");return{...line,key:actualRestaurant.id+":"+actualDish.id+":"+modifierKey,restaurantId:actualRestaurant.id,restaurantName:actualRestaurant.name,dish:actualDish,restaurantDeliveryFee:actualRestaurant.deliveryFee,freeDeliveryThreshold:actualRestaurant.freeDeliveryThreshold}}))},[ready,catalogReady,catalog]);
 useEffect(()=>{if(ready){localStorage.setItem("fuudgo-cart",JSON.stringify(cart));localStorage.setItem("fuudgo-mode",mode);localStorage.setItem("fuudgo-location",location);localStorage.setItem("fuudgo-saved",JSON.stringify(savedIds));localStorage.setItem("fuudgo-sounds",String(soundsEnabled))}},[cart,mode,location,savedIds,soundsEnabled,ready]);
 const userId=user?.id;
 useEffect(()=>{if(!userId)return;let live=true;void api<{data:{id:string}[]}>("/api/account/favourites").then(({data})=>{if(!live)return;const localMapped=savedIds.map(id=>{const source=catalog.find(r=>r.id===id)||restaurants.find(r=>r.id===id);return source?catalog.find(r=>r.slug===source.slug)?.id:null}).filter((id):id is string=>Boolean(id));const merged=[...new Set([...data.map(r=>r.id),...localMapped])];if(merged.length!==savedIds.length||merged.some(id=>!savedIds.includes(id)))setSavedIds(merged);for(const id of localMapped)if(!data.some(r=>r.id===id))void api(`/api/account/favourites/${id}`,{method:"POST"}).catch(()=>{})}).catch(()=>{});return()=>{live=false}},[userId,catalog,savedIds]);
 useEffect(()=>{const soundClick=(event:MouseEvent)=>{if(!soundsEnabled)return;const target=event.target;if(!(target instanceof Element))return;const control=target.closest("button,a,[role=button],select");if(!control||control.hasAttribute("disabled")||control.getAttribute("aria-disabled")==="true"||control.hasAttribute("data-silent"))return;try{const AudioCtor=window.AudioContext;if(!AudioCtor)return;const ctx=audioRef.current??(audioRef.current=new AudioCtor());if(ctx.state==="suspended")void ctx.resume();const now=ctx.currentTime,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type="sine";osc.frequency.setValueAtTime(620,now);osc.frequency.exponentialRampToValueAtTime(920,now+.045);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.045,now+.008);gain.gain.exponentialRampToValueAtTime(.0001,now+.075);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+.08)}catch{}};document.addEventListener("click",soundClick);return()=>document.removeEventListener("click",soundClick)},[soundsEnabled]);
 const setMode=useCallback((m:Mode)=>setModeState(m),[]);
 const setSoundsEnabled=useCallback((enabled:boolean)=>setSoundsEnabledState(enabled),[]);
 const refreshUser=useCallback(async()=>{try{const r=await api<{user:ApiUser}>("/api/user");setUser(r.user)}catch{setUser(null)}finally{setAuthReady(true)}},[]);
 const add=useCallback((restaurantId:string,dish:Dish,modifiers:ModifierSelection[]=[])=>
 {const r=catalog.find(x=>x.id===restaurantId);if(!r)return;const other=cart.length&&cart[0].restaurantId!==restaurantId;if(other){setPending(dish);setPendingRestaurant(restaurantId);setPendingModifiers(modifiers);return}const modifierKey=modifiers.map(g=>`${g.groupId}:${g.options.map(o=>o.id).sort().join(",")}`).join("|");setCart(old=>{const key=`${restaurantId}:${dish.id}:${modifierKey}`;const exists=old.find(x=>x.key===key);return exists?old.map(x=>x.key===key?{...x,quantity:x.quantity+1}:x):[...old,{key,restaurantId,restaurantName:r.name,dish,quantity:1,modifiers,restaurantDeliveryFee:r.deliveryFee,freeDeliveryThreshold:r.freeDeliveryThreshold}]})},[catalog,cart]);
 const resolve=useCallback((yes:boolean)=>{if(yes&&pending){const r=catalog.find(x=>x.id===pendingRestaurant);const modifierKey=pendingModifiers.map(g=>`${g.groupId}:${g.options.map(o=>o.id).sort().join(",")}`).join("|");if(r)setCart([{key:`${r.id}:${pending.id}:${modifierKey}`,restaurantId:r.id,restaurantName:r.name,dish:pending,quantity:1,modifiers:pendingModifiers,restaurantDeliveryFee:r.deliveryFee,freeDeliveryThreshold:r.freeDeliveryThreshold}])}setPending(null);setPendingRestaurant("");setPendingModifiers([])},[catalog,pending,pendingRestaurant,pendingModifiers]);
 const setQty=useCallback((key:string,n:number)=>setCart(old=>n<=0?old.filter(x=>x.key!==key):old.map(x=>x.key===key?{...x,quantity:n}:x)),[]);
 const remove=useCallback((key:string)=>setCart(old=>old.filter(x=>x.key!==key)),[]),clear=useCallback(()=>setCart([]),[]);
 const place=useCallback((o:Order)=>{setOrder(o);sessionStorage.setItem("fuudgo-order",JSON.stringify(o));setCart([])},[]);
 const toggleSaved=useCallback((id:string)=>{setSavedIds(old=>{const saved=old.includes(id);if(user)void api(`/api/account/favourites/${id}`,{method:"POST"}).catch(()=>{});return saved?old.filter(savedId=>savedId!==id):[...old,id]})},[user]);
 const value=useMemo(()=>({cart,mode,setMode,location,setLocation,pending,pendingRestaurant,add,resolve,setQty,remove,clear,order,place,savedIds,toggleSaved,soundsEnabled,setSoundsEnabled,restaurants:catalog,user,authReady,refreshUser}),[cart,mode,setMode,location,pending,pendingRestaurant,add,resolve,setQty,remove,clear,order,place,savedIds,toggleSaved,soundsEnabled,setSoundsEnabled,catalog,user,authReady,refreshUser]);
 return <Context.Provider value={value}>{children}{pending&&<div className="overlay" role="presentation"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="cart-warning"><div className="dialog-icon">⇄</div><h2 id="cart-warning">Start a new cart?</h2><p>Your cart has items from another restaurant. Starting a new cart will remove them.</p><div className="dialog-actions"><button className="button secondary" onClick={()=>resolve(false)}>Keep my cart</button><button className="button primary" onClick={()=>resolve(true)}>Clear cart & continue</button></div></div></div>}</Context.Provider>
}
export function useApp(){const v=useContext(Context);if(!v)throw new Error("useApp must be used inside AppProvider");return v}
