"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ArrowRight, ChevronDown, Clock3, Heart, MapPin, Minus, Plus, Search, ShoppingBag, Star, Volume2, VolumeX, X } from "lucide-react";
import { locations, imageFallback } from "@/data/restaurants";
import { money,totals } from "@/lib/cart";
import { useApp } from "@/components/app-provider";
import type { Restaurant,Dish,ModifierSelection } from "@/types";

export function FoodImage({src,alt,className=""}:{src:string;alt:string;className?:string}){const [failed,setFailed]=useState(false);return <div className={`food-image ${className}`}><img src={failed?imageFallback:src} alt={alt} loading="lazy" onError={()=>setFailed(true)}/></div>}
export function Header(){const {cart,mode,setMode,location,setLocation,savedIds,soundsEnabled,setSoundsEnabled,user}=useApp();const count=cart.reduce((a,x)=>a+x.quantity,0);return <header className="site-header"><div className="header-main wrap"><Link className="brand" href="/"><span className="brand-mark">f<span>g</span></span><span>fuud<span>go</span><small>GOOD FOOD, YOUR WAY</small></span></Link><div className="delivery-control"><span className="location-icon"><MapPin size={17}/></span><span className="location-copy"><small>{mode === "Delivery"?"Delivering to":"Browsing near"}</small><select aria-label="Choose Kuching area" value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(l=><option key={l}>{l}</option>)}</select></span><ChevronDown size={15}/></div><div className="header-actions"><Link href="/#restaurants" className="nav-link">Explore</Link><Link href="/restaurants" className="nav-link">Restaurants</Link><Link href={user?"/account":"/login"} className="nav-link">{user?"My account":"Sign in"}</Link><Link href="/saved" className="nav-link saved-link"><Heart size={16}/> Saved{savedIds.length>0&&<small>{savedIds.length}</small>}</Link><button type="button" className="sound-toggle" onClick={()=>setSoundsEnabled(!soundsEnabled)} aria-label={soundsEnabled?"Turn click sounds off":"Turn click sounds on"} aria-pressed={soundsEnabled} title={soundsEnabled?"Click sounds on":"Click sounds off"}>{soundsEnabled?<Volume2 size={18}/>:<VolumeX size={18}/>}<span>Sound {soundsEnabled?"on":"off"}</span></button><Link href="/checkout" className="cart-button" aria-label={`View cart, ${count} items`}><ShoppingBag size={19}/><span>Basket</span>{count>0&&<b>{count}</b>}</Link></div><Link className="mobile-saved" href="/saved" aria-label={`Saved restaurants, ${savedIds.length}`}><Heart size={19}/>{savedIds.length>0&&<b>{savedIds.length}</b>}</Link><button type="button" className="mobile-sound-toggle" onClick={()=>setSoundsEnabled(!soundsEnabled)} aria-label={soundsEnabled?"Turn click sounds off":"Turn click sounds on"} aria-pressed={soundsEnabled}>{soundsEnabled?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><Link className="mobile-cart" href="/checkout" aria-label={`View cart, ${count} items`}><ShoppingBag size={20}/>{count>0&&<b>{count}</b>}</Link></div><nav className="header-sub" aria-label="Ordering options"><div className="wrap sub-inner"><div className="mode-switch"><button className={mode==="Delivery"?"selected":""} onClick={()=>setMode("Delivery")}>🛵 <span>Delivery</span></button><button className={mode==="Pickup"?"selected":""} onClick={()=>setMode("Pickup")}>🏃 <span>Pickup</span></button></div><span className="demo-tag">A little taste of Kuching <span>•</span> Demo listings</span></div></nav></header>}
export function RestaurantCard({restaurant}:{restaurant:Restaurant}){const {mode,savedIds,toggleSaved}=useApp();const saved=savedIds.includes(restaurant.id);return <article className="restaurant-card"><div className="card-photo"><Link href={`/restaurant/${restaurant.slug}`} aria-label={`Open ${restaurant.name}`}><FoodImage src={restaurant.image} alt={`${restaurant.name} food`}/></Link>{restaurant.promotion&&<span className="deal-badge">{restaurant.promotion}</span>}<button className={`save-button ${saved?"saved":""}`} aria-label={saved?`Remove ${restaurant.name} from saved restaurants`:`Save ${restaurant.name}`} aria-pressed={saved} onClick={()=>toggleSaved(restaurant.id)}><Heart size={17} fill={saved?"currentColor":"none"}/></button></div><Link href={`/restaurant/${restaurant.slug}`} className="card-content"><div className="card-title"><h3>{restaurant.name}</h3><span className="rating"><Star size={13} fill="currentColor"/>{restaurant.rating.toFixed(1)}</span></div><p>{restaurant.cuisine.slice(0,2).join(" · ")} <span>·</span> {restaurant.tags[0]}</p><div className="card-meta"><span><Clock3 size={13}/>{mode==="Delivery"?restaurant.deliveryMinutes:restaurant.pickupMinutes} min</span><i>·</i><span>{mode==="Delivery"?restaurant.deliveryFee?money(restaurant.deliveryFee):"Free delivery":"Pickup"}</span></div></Link></article>}
export function SectionTitle({eyebrow,title,more}:{eyebrow?:string;title:string;more?:string}){return <div className="section-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{more&&<Link href="/restaurants" className="text-link">{more}<ArrowRight size={16}/></Link>}</div>}
export function DishCard({dish,restaurantId}:{dish:Dish;restaurantId:string}){
 const {add}=useApp();const [open,setOpen]=useState(false),[selected,setSelected]=useState<Record<number,number[]>>({}),[error,setError]=useState("");
 function start(){const groups=dish.modifierGroups||[];if(!groups.length){add(restaurantId,dish);return}const initial:Record<number,number[]>={};for(const group of groups)if(group.required||group.minimumSelections>0)initial[group.id]=group.options.slice(0,Math.max(group.required?1:0,group.minimumSelections)).map(o=>o.id);setSelected(initial);setError("");setOpen(true)}
 function choose(groupId:number,optionId:number,max:number){setSelected(current=>{const values=current[groupId]||[];return{...current,[groupId]:max===1?[optionId]:values.includes(optionId)?values.filter(id=>id!==optionId):values.length<max?[...values,optionId]:values}})}
 function confirm(){const groups=dish.modifierGroups||[];const missing=groups.find(g=>(selected[g.id]?.length||0)<Math.max(g.required?1:0,g.minimumSelections));if(missing){setError("Choose at least "+Math.max(missing.required?1:0,missing.minimumSelections)+" option(s) for "+missing.name+".");return}const choices:ModifierSelection[]=groups.map(g=>({groupId:g.id,groupName:g.name,options:g.options.filter(o=>(selected[g.id]||[]).includes(o.id))})).filter(g=>g.options.length);add(restaurantId,dish,choices);setOpen(false)}
 return <><article className={"dish-card "+(!dish.available?"unavailable":"")}><FoodImage src={dish.image} alt={dish.name}/><div className="dish-info"><div className="dish-top"><div>{dish.popular&&<span className="popular-label">✦ Local favourite</span>}<h3>{dish.name}</h3><p>{dish.description}</p></div><button className="add-button" disabled={!dish.available} onClick={start} aria-label={"Customize and add "+dish.name}><Plus size={17}/></button></div><div className="dish-bottom"><strong>{money(dish.promoPrice??dish.price)}</strong>{dish.modifierGroups?.length?<small>Customise</small>:null}{dish.promoPrice&&<del>{money(dish.price)}</del>}{!dish.available&&<span>Unavailable</span>}</div></div></article>{open&&<div className="overlay" role="presentation"><section className="dialog modifier-dialog" role="dialog" aria-modal="true" aria-labelledby={"customize-"+dish.id}><button className="dialog-close" aria-label="Close" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">MAKE IT YOURS</span><h2 id={"customize-"+dish.id}>{dish.name}</h2><p>Choose the extras you’d like.</p>{(dish.modifierGroups||[]).map(group=><fieldset className="modifier-group" key={group.id}><legend>{group.name} <small>{group.required||group.minimumSelections>0?"Required":"Optional"} · Choose up to {group.maximumSelections}</small></legend>{group.options.map(option=><label key={option.id} className="modifier-option"><input type={group.maximumSelections===1?"radio":"checkbox"} name={"group-"+group.id} checked={(selected[group.id]||[]).includes(option.id)} onChange={()=>choose(group.id,option.id,group.maximumSelections)}/><span>{option.name}</span><b>{option.priceAdjustment?"+ "+money(option.priceAdjustment):"Included"}</b></label>)}</fieldset>)}{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary full-button" onClick={confirm}>Add to basket <Plus size={17}/></button></section></div>}</>
}
export function Quantity({value,onChange}:{value:number;onChange:(n:number)=>void}){return <div className="quantity"><button aria-label="Decrease quantity" onClick={()=>onChange(value-1)}><Minus size={13}/></button><span>{value}</span><button aria-label="Increase quantity" onClick={()=>onChange(value+1)}><Plus size={13}/></button></div>}
export function SearchBox({value,onChange,placeholder="Search restaurants, dishes and cuisines"}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="search-box"><Search size={19}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button aria-label="Clear search" onClick={()=>onChange("")}><X size={16}/></button>}</label>}
export function Footer(){return <footer className="footer"><div className="wrap footer-inner"><div className="brand footer-brand"><span className="brand-mark">f<span>g</span></span><span>fuud<span>go</span><small>GOOD FOOD, YOUR WAY</small></span></div><p>Made for Kuching cravings.<br/>A local ordering experience, one good meal at a time.</p><small>© 2026 FuudGo · Prototype experience</small></div></footer>}
export function CartDock(){const {cart,mode}=useApp();const pathname=usePathname();if(!cart.length||pathname==="/checkout"||pathname.startsWith("/order/"))return null;const count=cart.reduce((sum,line)=>sum+line.quantity,0),sum=totals(cart,mode);return <Link href="/checkout" className="cart-dock" aria-label={`Open basket with ${count} ${count===1?"item":"items"}, total ${money(sum.total)}`}><span className="dock-icon"><ShoppingBag size={23}/><b>{count}</b></span><span className="dock-copy"><strong>Your basket</strong><small>{count} {count===1?"item":"items"}</small></span><span className="dock-total">{money(sum.total)}<span>View</span><ArrowRight size={19}/></span></Link>}
