"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { api, ApiError, type ApiAddress } from "@/lib/api";
import { useApp } from "@/components/app-provider";
import { money } from "@/lib/cart";

type AccountOrder={reference:string;restaurant:string;restaurantSlug:string;fulfilment:string;status:string;paymentStatus:string;total:number;placedAt:string};
type SavedAddress=ApiAddress&{recipient_name:string;phone:string;line_1:string;line_2:string|null;delivery_instructions:string|null;is_default:boolean};
export default function AccountPage(){const {user,authReady,refreshUser}=useApp();const router=useRouter();const [orders,setOrders]=useState<AccountOrder[]>([]),[addresses,setAddresses]=useState<SavedAddress[]>([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(authReady&&!user)router.replace(`/login?returnTo=${encodeURIComponent("/account")}`)},[authReady,user,router]);
 useEffect(()=>{if(!user)return;void Promise.all([api<{data:AccountOrder[]}>("/api/account/orders"),api<{data:SavedAddress[]}>("/api/account/addresses")]).then(([o,a])=>{setOrders(o.data);setAddresses(a.data)}).catch(()=>setError("We couldn't load your account details. Refresh and try again."))},[user]);
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setMessage("");setBusy(true);const fd=new FormData(e.currentTarget);try{await api("/api/account/profile",{method:"PATCH",body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),phone:fd.get("phone")})});await refreshUser();setMessage("Your details are saved.")}catch(err){setError(err instanceof ApiError?err.message:"We couldn't save your details.")}finally{setBusy(false)}}
 async function addAddress(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const fd=new FormData(e.currentTarget);const payload=Object.fromEntries(fd.entries());try{const r=await api<{data:SavedAddress}>("/api/account/addresses",{method:"POST",body:JSON.stringify({...payload,is_default:fd.get("is_default")==="on"})});setAddresses(list=>[...list,r.data]);e.currentTarget.reset();setMessage("Address added.")}catch(err){setError(err instanceof ApiError?err.message:"We couldn't save that address.")}}
 async function removeAddress(id:number){try{await api(`/api/account/addresses/${id}`,{method:"DELETE"});setAddresses(list=>list.filter(a=>a.id!==id))}catch{setError("We couldn't remove that address.")}}
 async function logout(){await api("/api/logout",{method:"POST"}).catch(()=>{});await refreshUser();router.replace("/")}
 if(!authReady||!user)return <div className="wrap all-restaurants"><p>Loading your FuudGo account…</p></div>;
 return <div className="wrap all-restaurants account-page"><span className="eyebrow">YOUR FUUDGO</span><h1>Hey, {user.name.split(" ")[0]}.</h1><p>Your details, addresses and latest good things.</p>{error&&<p role="alert" className="error-text">{error}</p>}{message&&<p role="status" className="success-note">{message}</p>}<div className="account-grid"><section className="checkout-card"><h2>Your details</h2><form className="auth-form" onSubmit={saveProfile}><label className="form-field">Name<input name="name" defaultValue={user.name} required/></label><label className="form-field">Email<input type="email" name="email" defaultValue={user.email} required/></label><label className="form-field">Phone<input name="phone" defaultValue={user.phone||""}/></label><button className="button primary" disabled={busy}>{busy?"Saving…":"Save details"}</button></form><button className="button secondary" onClick={logout}>Sign out</button></section><section className="checkout-card"><h2>Saved addresses</h2>{addresses.map(a=><article className="account-address" key={a.id}><div><b>{a.label}{a.is_default?" · Default":""}</b><p>{a.line_1}{a.line_2?`, ${a.line_2}`:""}, {a.area}</p></div><button className="text-link" onClick={()=>removeAddress(a.id)}>Remove</button></article>)}<details className="address-add"><summary className="button secondary">Add an address</summary><form className="auth-form" onSubmit={addAddress}><label className="form-field">Label<input name="label" placeholder="Home" required/></label><label className="form-field">Recipient name<input name="recipient_name" defaultValue={user.name} required/></label><label className="form-field">Phone<input name="phone" defaultValue={user.phone||""} required/></label><label className="form-field">Address line<input name="line_1" required/></label><label className="form-field">Unit / building<input name="line_2"/></label><label className="form-field">Kuching area<input name="area" required/></label><label className="form-field">Delivery notes<textarea name="delivery_instructions"/></label><label><input type="checkbox" name="is_default"/> Make default</label><button className="button primary">Save address</button></form></details></section><section className="checkout-card account-orders"><h2>Your orders</h2>{orders.length?orders.map(o=><article className="account-order" key={o.reference}><div><b>{o.restaurant}</b><p>{o.reference} · {new Date(o.placedAt).toLocaleDateString()}</p><small>{o.status.replaceAll("_"," ")} · {o.paymentStatus}</small></div><b>{money(o.total)}</b></article>):<p>No orders yet. <Link href="/restaurants">Find something tasty.</Link></p>}</section></div></div>
}
